In [1]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chidv\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

## Step 1: Data Loading

In [2]:

badminton = pd.read_csv(r"D:\DS\Projects\GEN_AI\TASK_2\Sentiment Analysis\reviews_badminton\data.csv")
tawa = pd.read_csv(r"D:\DS\Projects\GEN_AI\TASK_2\Sentiment Analysis\reviews_tawa\data.csv")
tea = pd.read_csv(r"D:\DS\Projects\GEN_AI\TASK_2\Sentiment Analysis\reviews_tea\data.csv")

In [3]:
tea.shape

(9170, 8)

In [4]:
tawa.columns

Index(['Reviewer_Name', 'Reviewer_Rating', 'Review_Title', 'Review_Text',
       'Place_of_Review', 'Date_of_Review', 'Up_Votes', 'Down_Votes'],
      dtype='object')

In [5]:
badminton.columns

Index(['Reviewer Name', 'Review Title', 'Place of Review', 'Up Votes',
       'Down Votes', 'Month', 'Review text', 'Ratings'],
      dtype='object')

In [6]:
tea.columns

Index(['reviewer_name', 'reviewer_rating', 'review_title', 'review_text',
       'place_of_review', 'Date_of_review', 'up_votes', 'Down_votes'],
      dtype='object')

## Step 2: Data Cleaning

In [7]:
badminton.columns = badminton.columns.str.strip().str.lower().str.replace(" ", "_")

badminton.rename(columns={
    'ratings': 'reviewer_rating'
}, inplace=True)

In [8]:
tawa.columns = tawa.columns.str.strip().str.lower().str.replace(" ", "_")

In [9]:
tea.columns = tea.columns.str.strip().str.lower().str.replace(" ", "_")

In [10]:
print(badminton.columns)
print(tawa.columns)
print(tea.columns)

Index(['reviewer_name', 'review_title', 'place_of_review', 'up_votes',
       'down_votes', 'month', 'review_text', 'reviewer_rating'],
      dtype='object')
Index(['reviewer_name', 'reviewer_rating', 'review_title', 'review_text',
       'place_of_review', 'date_of_review', 'up_votes', 'down_votes'],
      dtype='object')
Index(['reviewer_name', 'reviewer_rating', 'review_title', 'review_text',
       'place_of_review', 'date_of_review', 'up_votes', 'down_votes'],
      dtype='object')

In [11]:
badminton['date_of_review'] = None
badminton.drop(columns=['month'], inplace=True)

In [12]:
columns_order = [
    'reviewer_name', 'reviewer_rating', 'review_title',
    'review_text', 'place_of_review', 'date_of_review',
    'up_votes', 'down_votes'
]

badminton = badminton[columns_order]
tawa = tawa[columns_order]
tea = tea[columns_order]

In [13]:
badminton.loc[:, 'product'] = 'badminton'
tawa.loc[:, 'product'] = 'tawa'
tea.loc[:, 'product'] = 'tea'

In [14]:
df = pd.concat([badminton, tawa, tea], ignore_index=True)

In [15]:
df

,reviewer_name,reviewer_rating,review_title,review_text,place_of_review,date_of_review,up_votes,down_votes,product
0,Kamal Suresh,4.0,Nice product,"Nice product, good quality, but price is now r...","Certified Buyer, Chirakkal",None,889.0,64.0,badminton
1,Flipkart Customer,1.0,Don't waste your money,They didn't supplied Yonex Mavis 350. Outside ...,"Certified Buyer, Hyderabad",None,109.0,6.0,badminton
2,A. S. Raja Srinivasan,1.0,Did not meet expectations,Worst product. Damaged shuttlecocks packed in ...,"Certified Buyer, Dharmapuri",None,42.0,3.0,badminton
3,Suresh Narayanasamy,3.0,Fair,"Quite O. K. , but nowadays the quality of the...","Certified Buyer, Chennai",None,25.0,1.0,badminton
4,ASHIK P A,1.0,Over priced,Over pricedJust â?¹620 ..from retailer.I didn'...,NaN,None,147.0,24.0,badminton
...,...,...,...,...,...,...,...,...,...
20214,Omm Prakash,5.0,Simply awesome,Nice for red tea.Valeu for moneyREAD MORE,"Certified Buyer, Dhamanagar",Omm Prakash,26.0,5.0,tea
20215,Ritu Raj,4.0,Good choice,niceREAD MORE,"Certified Buyer, Katihar District",Ritu Raj,19.0,4.0,tea
20216,Arun Saini,1.0,Terrible product,Tata Gold Vs Tata Tea Premium👍Tata Tea Premiu...,"Certified Buyer, Haridwar",Arun Saini,13.0,2.0,tea
20217,Amitabh Shahi,5.0,Just wow!,I believe that it's the best packaged tea in t...,"Certified Buyer, Darbhanga",Amitabh Shahi,32.0,10.0,tea
20218,Rohan Bhowmik,5.0,Simply awesome,Very good product.READ MORE,"Certified Buyer, Paschim Medinipur District",Rohan Bhowmik,69.0,29.0,tea

In [16]:
df.shape

(20219, 9)

In [17]:
df.isna().sum()

reviewer_name        10
reviewer_rating     246
review_title         10
review_text           8
place_of_review      50
date_of_review     8518
up_votes             10
down_votes           10
product               0
dtype: int64

In [18]:
df = df.drop(columns=['date_of_review'])

In [19]:
df['review_title'] = df['review_title'].fillna("")
df['place_of_review'] = df['place_of_review'].fillna("unknown")
df['reviewer_rating'] = df['reviewer_rating'].fillna(df['reviewer_rating'].mean())

In [20]:
df['review_text'] = df['review_text'].fillna("")

In [21]:
df.isna().sum()

reviewer_name      10
reviewer_rating     0
review_title        0
review_text         0
place_of_review     0
up_votes           10
down_votes         10
product             0
dtype: int64

In [22]:
df

,reviewer_name,reviewer_rating,review_title,review_text,place_of_review,up_votes,down_votes,product
0,Kamal Suresh,4.0,Nice product,"Nice product, good quality, but price is now r...","Certified Buyer, Chirakkal",889.0,64.0,badminton
1,Flipkart Customer,1.0,Don't waste your money,They didn't supplied Yonex Mavis 350. Outside ...,"Certified Buyer, Hyderabad",109.0,6.0,badminton
2,A. S. Raja Srinivasan,1.0,Did not meet expectations,Worst product. Damaged shuttlecocks packed in ...,"Certified Buyer, Dharmapuri",42.0,3.0,badminton
3,Suresh Narayanasamy,3.0,Fair,"Quite O. K. , but nowadays the quality of the...","Certified Buyer, Chennai",25.0,1.0,badminton
4,ASHIK P A,1.0,Over priced,Over pricedJust â?¹620 ..from retailer.I didn'...,unknown,147.0,24.0,badminton
...,...,...,...,...,...,...,...,...
20214,Omm Prakash,5.0,Simply awesome,Nice for red tea.Valeu for moneyREAD MORE,"Certified Buyer, Dhamanagar",26.0,5.0,tea
20215,Ritu Raj,4.0,Good choice,niceREAD MORE,"Certified Buyer, Katihar District",19.0,4.0,tea
20216,Arun Saini,1.0,Terrible product,Tata Gold Vs Tata Tea Premium👍Tata Tea Premiu...,"Certified Buyer, Haridwar",13.0,2.0,tea
20217,Amitabh Shahi,5.0,Just wow!,I believe that it's the best packaged tea in t...,"Certified Buyer, Darbhanga",32.0,10.0,tea
20218,Rohan Bhowmik,5.0,Simply awesome,Very good product.READ MORE,"Certified Buyer, Paschim Medinipur District",69.0,29.0,tea

## Step 3: Text Preprocessing

## Starting ML flow

In [ ]:
import mlflow

mlflow.set_tracking_uri(
    "http://localhost:5000"
)
mlflow.openai.autolog()

In [29]:

mlflow.set_experiment("Sentiment Analysis")

2026/04/03 15:49:54 INFO mlflow.tracking.fluent: Experiment with name 'Sentiment Analysis' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/1', creation_time=1775211594849, experiment_id='1', last_update_time=1775211594849, lifecycle_stage='active', name='Sentiment Analysis', tags={}, workspace='default'>

In [27]:
def get_sentiment(rating):
    if rating >= 4:
        return 'positive'
    else:
        return 'negative'

df['sentiment'] = df['reviewer_rating'].apply(get_sentiment)

In [30]:
df[['reviewer_rating', 'sentiment']].head()

   reviewer_rating sentiment
0              4.0  positive
1              1.0  negative
2              1.0  negative
3              3.0  negative
4              1.0  negative

In [31]:
def clean_text(text):
    if pd.isnull(text):   # handle NaN
        return ""
    
    text = re.sub(r'[^a-zA-Z]', ' ', str(text))
    text = text.lower()
    words = text.split()
    words = [w for w in words if w not in stopwords.words('english')]
    return " ".join(words)

df['clean_text'] = df['review_text'].apply(clean_text)

## Step 4: Feature Engineering

In [32]:

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['clean_text'])

In [33]:
y = df['sentiment']

In [34]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 128917 stored elements and shape (20219, 3805)>

In [35]:
y

0        positive
1        negative
2        negative
3        negative
4        negative
           ...
20214    positive
20215    positive
20216    negative
20217    positive
20218    positive
Name: sentiment, Length: 20219, dtype: object

### Train-Test Split

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [37]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(16175, 3805) (4044, 3805) (16175,) (4044,)

In [38]:
y_train = y_train.values
y_test = y_test.values

## Model building

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

2026/04/03 16:09:19 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

2026/04/03 16:09:21 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'd55a80802e9e4442b75bf2f80ebf9e94', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2026/04/03 16:09:25 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run sincere-quail-301 at: http://localhost:5000/#/experiments/1/runs/d55a80802e9e4442b75bf2f80ebf9e94
🧪 View experiment at: http://localhost:5000/#/experiments/1

LogisticRegression()

In [40]:
training_score= model.score(X_train, y_train)
training_score

0.9382998454404946

In [41]:
y_pred = model.predict(X_test)

## 5 Model Evaluation or test metrics

In [42]:
from sklearn.metrics import classification_report, f1_score

print(classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

              precision    recall  f1-score   support

    negative       0.87      0.55      0.68       615
    positive       0.92      0.98      0.95      3429

    accuracy                           0.92      4044
   macro avg       0.90      0.77      0.82      4044
weighted avg       0.92      0.92      0.91      4044

F1 Score: 0.9117735428846051

### Model 2 -- Support vector Machine

In [43]:
from sklearn import svm
clf = svm.SVC()

In [44]:
clf

SVC()

In [45]:
clf.fit(X_train, y_train)

2026/04/03 16:13:58 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'a7d827b3927c4dbd9488a9563ef58b9f', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2026/04/03 16:14:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run dazzling-loon-915 at: http://localhost:5000/#/experiments/1/runs/a7d827b3927c4dbd9488a9563ef58b9f
🧪 View experiment at: http://localhost:5000/#/experiments/1

SVC()

In [91]:
training_score=clf.score(X_train, y_train)
training_score

0.960370942812983

## There fore test score == 93% , train accuracy == 91% so model is `Generalising `

## Model 3 - naive_bayes

In [46]:
from sklearn.naive_bayes import GaussianNB

In [47]:
gnb = GaussianNB()

In [48]:
X_train=X_train.toarray()

In [49]:
gnb.fit(X_train, y_train)

2026/04/03 16:18:33 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'c4c54603845443d6a90fb9b5000187cb', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2026/04/03 16:18:38 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run smiling-whale-27 at: http://localhost:5000/#/experiments/1/runs/c4c54603845443d6a90fb9b5000187cb
🧪 View experiment at: http://localhost:5000/#/experiments/1

GaussianNB()

In [50]:
training_score=gnb.score(X_train, y_train)
training_score

0.4903245749613601

In [51]:
y_pred = gnb.predict(X_test.toarray())

In [52]:
print(classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

              precision    recall  f1-score   support

    negative       0.20      0.89      0.33       615
    positive       0.95      0.37      0.54      3429

    accuracy                           0.45      4044
   macro avg       0.58      0.63      0.43      4044
weighted avg       0.84      0.45      0.50      4044

F1 Score: 0.5043405559984586

## There fore test score == 50% , train accuracy == 49%

## Model 4 -- RandomForestClassifier

In [53]:
from  sklearn.ensemble import RandomForestClassifier
RC=RandomForestClassifier()
RC.fit(X_train, y_train)

2026/04/03 16:20:06 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '6a9a90092ca942bf883b2ef610719799', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2026/04/03 16:21:52 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run melodic-lamb-437 at: http://localhost:5000/#/experiments/1/runs/6a9a90092ca942bf883b2ef610719799
🧪 View experiment at: http://localhost:5000/#/experiments/1

RandomForestClassifier()

In [54]:
RC.score(X_train, y_train)

0.9721792890262752

In [55]:
y_pred = RC.predict(X_test.toarray())
print(classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

              precision    recall  f1-score   support

    negative       0.81      0.60      0.69       615
    positive       0.93      0.97      0.95      3429

    accuracy                           0.92      4044
   macro avg       0.87      0.79      0.82      4044
weighted avg       0.91      0.92      0.91      4044

F1 Score: 0.9126293211608364

## There fore test score == 91% , train accuracy == 97%

## Model 5 --  DTree

In [56]:
from sklearn import tree
dt = tree.DecisionTreeClassifier()
dt.fit(X_train, y_train)

2026/04/03 16:23:04 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'f895a51701d748e4bda3a48ef21e1166', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

2026/04/03 16:23:39 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run salty-conch-311 at: http://localhost:5000/#/experiments/1/runs/f895a51701d748e4bda3a48ef21e1166
🧪 View experiment at: http://localhost:5000/#/experiments/1

DecisionTreeClassifier()

In [57]:
dt.score(X_train, y_train)

0.9721792890262752

In [58]:
y_pred = dt.predict(X_test.toarray())

In [59]:
print(classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

              precision    recall  f1-score   support

    negative       0.71      0.69      0.70       615
    positive       0.94      0.95      0.95      3429

    accuracy                           0.91      4044
   macro avg       0.83      0.82      0.82      4044
weighted avg       0.91      0.91      0.91      4044

F1 Score: 0.9090044736032082

## Therefore test score == 90% , train accuracy == 97%

## Model 6 -- K-Nearest Neighbors

In [60]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train, y_train)

2026/04/03 16:26:40 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '404aabdb282647a9b2906de5c3703454', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
2026/04/03 16:26:45 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run gifted-elk-292 at: http://localhost:5000/#/experiments/1/runs/404aabdb282647a9b2906de5c3703454
🧪 View experiment at: http://localhost:5000/#/experiments/1

KNeighborsClassifier()

In [61]:
knn.score(X_train, y_train)

0.920370942812983

In [62]:
y_pred = knn.predict(X_test)
print(classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

              precision    recall  f1-score   support

    negative       0.88      0.44      0.59       615
    positive       0.91      0.99      0.95      3429

    accuracy                           0.91      4044
   macro avg       0.89      0.72      0.77      4044
weighted avg       0.90      0.91      0.89      4044

F1 Score: 0.8923821824793999

## There fore test score == 89% , train accuracy == 92%

### WE DECLARE `LOGISTIC REGRESSION` WILL BE BEST FIT SENTEMENT ANALYSIS

In [65]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(
    C=1.0,
    class_weight=None,
    dual=False,
    fit_intercept=True,
    intercept_scaling=1,
    l1_ratio=0.0,
    max_iter=100,
    n_jobs=None,
    penalty=None,
    random_state=None,
    solver='lbfgs',
    tol=0.0001,
    verbose=0,
    warm_start=False
)

model.fit(X_train, y_train)

2026/04/03 17:03:31 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '07e098c18dc34797b54e56b81d33f069', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow
c:\Users\chidv\.conda\envs\batch405\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\chidv\.conda\envs\batch405\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
2026/04/03 17:03:43 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run powerful-skink-484 at: http://localhost:5000/#/experiments/1/runs/07e098c18dc34797b54e56b81d33f069
🧪 View experiment at: http://localhost:5000/#/experiments/1

LogisticRegression(penalty=None)

In [66]:
knn.score(X_train, y_train)

0.920370942812983

In [67]:
y_pred = knn.predict(X_test)
print(classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

              precision    recall  f1-score   support

    negative       0.88      0.44      0.59       615
    positive       0.91      0.99      0.95      3429

    accuracy                           0.91      4044
   macro avg       0.89      0.72      0.77      4044
weighted avg       0.90      0.91      0.89      4044

F1 Score: 0.8923821824793999